"""add user relationship to instruments

Revision ID: b3cd3d65dee3
Revises: 064edebad568
Create Date: 2026-07-20 18:13:13.514255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3cd3d65dee3'
down_revision: Union[str, Sequence[str], None] = '064edebad568'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'instruments', 'Users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'instruments', type_='foreignkey')
    op.drop_column('instruments', 'user_id')
    # ### end Alembic commands ###
